<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Testing.TestServer</PackageId>
<Description>In-memory test server helpers</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>