<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
    <EnableMicrosoftTestingPlatform>false</EnableMicrosoftTestingPlatform>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>
    <RootNamespace>Novolis.Testing.WalkthroughIndex</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Testing.Playwright\Novolis.Testing.Playwright.csproj" />
  </ItemGroup>
</Project>
