<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Testing.TUnit</PackageId>
    <Description>TUnit test output extensions (tables, JSON, C# dump).</Description>
    <IsPackable>true</IsPackable>
    <OutputType>Library</OutputType>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Novolis.CodeGen.Reflection.Dump" />
    <ProjectReference Include="..\Novolis.Testing.TestBases\Novolis.Testing.TestBases.csproj" />
    
    <PackageReference Include="ConsoleTableExt" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="VarDump" />
  </ItemGroup>
</Project>
