<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Testing.TUnit</PackageId>
    <Version>0.1.0-preview.1</Version>
    <Description>xUnit test output extensions</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
      <PropertyGroup><RootNamespace>Xunit.Abstractions</RootNamespace></PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\Novolis.Testing.TestBases\Novolis.Testing.TestBases.csproj" />
      <PackageReference Include="ConsoleTableExt" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
      <PackageReference Include="TUnit.Core" />
      <PackageReference Include="Humanizer.Core" />
      <PackageReference Include="VarDump" />
    </ItemGroup>
</Project>
