<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Novolis.Testing.TestBases</PackageId>
<Description>Test host bases for integration tests (TUnit).</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="HostApplicationDependencyInjectionDataProviderAttributeBase.cs" />
  </ItemGroup>
</Project>