<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Novolis.Testing.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Novolis.Testing.Logging\Novolis.Testing.Logging.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Testing.TestBases\Novolis.Testing.TestBases.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Testing.TestServer\Novolis.Testing.TestServer.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Testing.TUnit\Novolis.Testing.TUnit.csproj" />
  </ItemGroup>
</Project>
